# Habilitar el deep sleep (ahorra muchísima batería)
CONFIG_ZMK_SLEEP=y

# Tiempo de inactividad antes del deep sleep (900000 ms = 15 minutos)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Incrementar la potencia del Bluetooth para conexión estable entre mitades
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Definir el nombre del teclado para la conexión Bluetooth
CONFIG_ZMK_KEYBOARD_NAME="Ergo-HW-Split"