# Habilitar el deep sleep (ahorra muchísima batería)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Incrementar la potencia del Bluetooth (ayuda con la conexión entre las dos mitades)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y